export enum ProjectCategory {
  SPORT ="SPORT",
  EDUCATION ="EDUCATION",
  CULTURE ="CULTURE",
  HEALTH ="HEALTH",
  ENVIRONMENT ="ENVIRONMENT",
  INFRASTRUCTURE ="INFRASTRUCTURE",
  NATURE ="NATURE",
  COMMUNITY ="COMMUNITY",
  OTHER ="OTHER"
}
